namespace: samdoran
name: net
version: 0.0.1
readme: README.md
authors:
  - Sam Doran <github@samdoran.com>

description: Roles for managing network services

license:
  - GPL-3.0-or-later

tags:
  - system
  - network

dependencies: {}

repository: http://github.com/samdoran/ansible-collection-net
documentation: http://github.com/samdoran/ansible-collection-net/README.md
homepage: http://github.com/samdoran/ansible-collection-net
issues: http://github.com/samdoran/ansible-collection-net/issues

build_ignore: []
